spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ENC(9XznOxvmierSowwBqv1mSk5KLPlShbUN6A5SvvppNpbHng14j0RoLTzkAQKqMpdT)
#    username: ENC(yixVQ9U6WusuQMa34v+P8Q==)
#    password: ENC(td4ZLVKdNy5JsVcp5yvuXsL0vGidbphp)
    url: jdbc:mysql://10.0.1.12:3306/lab2db
    username: student
    password: abc123!@#

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: "file:/run/secrets/jasypt_password"